name: amass
version: 'v2.4.1'
summary: In-Depth DNS Enumeration
description: |
  The OWASP Amass tool obtains subdomain names by scraping data sources, 
  recursive brute forcing, crawling web archives, permuting/altering names 
  and reverse DNS sweeping. Additionally, Amass uses the IP addresses 
  obtained during resolution to discover associated netblocks and ASNs. All 
  the information is then used to build maps of the target networks.
icon: images/snapcraft_icon.png
grade: stable
confinement: strict


apps:
  amass:
    command: bin/amass
    plugs: [home, network, removable-media]

  maltego:
    command: bin/maltego
    plugs: [home, network, removable-media]


parts:
  go:
    source-tag: go1.10

  amass:
    after: [go]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      go build -o $GOPATH/bin/amass main.go
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOPATH/bin/amass $SNAPCRAFT_PART_INSTALL/bin/amass
  
  maltego:
    after: [go]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      export GOBIN=$GOPATH/bin
      go install maltego/amass_maltego.go
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOBIN/amass_maltego $SNAPCRAFT_PART_INSTALL/bin/maltego